### PR TITLE
dead link 

### PR DESCRIPTION
**Pull request by replicatedbart**
[sample YAML for common SMTP inputs] was pointing to old support site

### CODE REVIEW

**Comment by stephenlawrence** [comment]
After looking at this further I think all of those sentences can just be removed. It looks like they were sending visitors to a separate section of the docs to see the example, but now we have the example embedded below.

**Comment by emosbaugh** [comment]
@replicatedbart please update the pr per steves suggestion and remove those sections. thanks

**Comment by replicatedbart** [comment]
removed links, please review

**Comment by stephenlawrence** [comment]
lgtm

**Pull request merged**
